import type { Dimension, Group } from "./types.js";

/** One group: its stable machine id and its human-readable display label. */
export interface GroupDef {
  id: Group;
  label: string;
}

/** The seven dimension groups in display order. */
export const GROUP_ORDER: readonly GroupDef[] = [
  { id: "communication-style", label: "Communication" },
  { id: "cognitive-style", label: "Cognitive" },
  { id: "personality-big-five", label: "Personality (Big Five)" },
  { id: "motivation-values", label: "Motivation & Values" },
  { id: "affective-emotional", label: "Affective / Emotional" },
  { id: "domain-aptitude", label: "Domain Aptitude" },
  { id: "interaction-behavioral", label: "Interaction / Behavioral" },
];

/**
 * The scoring dimensions, grouped into seven categories. Each dimension is a
 * TypeSafe `score` question: `instructions` asks about one message and `rubric`
 * describes five ordered levels (0 = low end, 4 = high end). The normalized
 * score is `answer.score / 4`.
 *
 * Every dimension records two schema facts: a monotonic `direction` (a high
 * score always means "more of" the named trait) and a `polarity` (whether that
 * high score is `desirable`, `diagnostic`, or `inverted-risk`). `basis` records
 * what the score is inferred from — text for every current dimension.
 */
export const DIMENSIONS: readonly Dimension[] = [
  // ---- A. Communication style ----
  {
    id: "clarity",
    category: "Communication",
    group: "communication-style",
    label: "Clarity",
    polarity: "desirable",
    direction: "high = clearer, more understandable",
    basis: "text",
    instructions: "How clear and understandable is this message?",
    rubric: [
      "Opaque, confusing, or ambiguous; hard to tell what is meant",
      "Somewhat unclear; requires effort or guessing to follow",
      "Mostly understandable with occasional vagueness",
      "Clear and easy to follow",
      "Exceptionally clear, precise, and unambiguous",
    ],
  },
  {
    id: "technical_accuracy",
    category: "Communication",
    group: "communication-style",
    label: "Technical accuracy",
    polarity: "desirable",
    direction: "high = more factually/technically correct",
    basis: "text",
    instructions: "How factually and technically correct are the claims in this message?",
    rubric: [
      "Contains clear errors or misinformation",
      "Mostly incorrect or unsubstantiated",
      "Partially correct with notable inaccuracies",
      "Largely accurate with minor imprecision",
      "Fully accurate and technically correct",
    ],
    note: "Apparent soundness only; unverifiable without ground truth.",
  },
  {
    id: "actionability",
    category: "Communication",
    group: "communication-style",
    label: "Actionability",
    polarity: "desirable",
    direction: "high = more concrete, executable, immediately useful",
    basis: "text",
    instructions: "How concrete, executable, and immediately useful is this message?",
    rubric: [
      "Abstract with no concrete steps or next actions",
      "Vague; next steps are unclear or only implied",
      "Some concrete detail but incomplete guidance",
      "Concrete with clear, executable steps",
      "Fully actionable; specific, immediately executable guidance",
    ],
  },
  {
    id: "completeness",
    category: "Communication",
    group: "communication-style",
    label: "Completeness",
    polarity: "desirable",
    direction: "high = more thorough, fewer gaps",
    basis: "text",
    instructions: "How thorough is this message, with few gaps in necessary detail?",
    rubric: [
      "Missing critical information; major gaps",
      "Notably incomplete; important context omitted",
      "Some gaps; partial coverage",
      "Thorough; covers needed detail",
      "Complete with all relevant detail, no meaningful gaps",
    ],
    note: "Over-completeness/verbosity is captured separately as low signal-to-noise.",
  },
  {
    id: "tone_sentiment",
    category: "Communication",
    group: "communication-style",
    label: "Tone / sentiment",
    polarity: "diagnostic",
    direction: "high = more positive, constructive",
    basis: "text",
    instructions: "How positive and constructive is the emotional tone of this message?",
    rubric: [
      "Strongly negative, hostile, or destructive",
      "Mostly negative or critical",
      "Neutral or mixed",
      "Positive and constructive",
      "Warm, encouraging, and constructive",
    ],
  },
  {
    id: "formality",
    category: "Communication",
    group: "communication-style",
    label: "Formality",
    polarity: "diagnostic",
    direction: "high = more formal, structured register",
    basis: "text",
    instructions: "How formal and structured is the register of this message?",
    rubric: [
      "Very casual; slang, shorthand, no structure",
      "Informal and conversational",
      "Neutral register",
      "Formal and structured",
      "Highly formal, polished, precise register",
    ],
  },
  {
    id: "concreteness",
    category: "Communication",
    group: "communication-style",
    label: "Concreteness",
    polarity: "diagnostic",
    direction: "high = more specific, concrete (vs. abstract)",
    basis: "text",
    instructions: "How concrete and specific (vs. abstract and general) is this message's language?",
    rubric: [
      "Entirely abstract, vague, or theoretical",
      "Mostly abstract with little specificity",
      "Mixed abstract and concrete",
      "Mostly concrete and specific",
      "Rich in specific, concrete detail",
    ],
  },
  {
    id: "signal_to_noise",
    category: "Communication",
    group: "communication-style",
    label: "Signal-to-noise ratio",
    polarity: "desirable",
    direction: "high = more information-dense, less filler",
    basis: "text",
    instructions: "How information-dense is this message, with minimal filler or fluff?",
    rubric: [
      "Almost all filler, repetition, or noise; little substance",
      "Mostly filler with some substance",
      "Balanced but with noticeable filler",
      "Mostly substantive and dense",
      "Maximally information-dense; no filler",
    ],
  },

  // ---- B. Cognitive style ----
  {
    id: "need_for_cognition",
    category: "Cognitive",
    group: "cognitive-style",
    label: "Need for cognition",
    polarity: "diagnostic",
    direction: "high = more reflective, deliberative thinking",
    basis: "text",
    instructions: "How much does this message reflect reflective, deliberative, effortful thinking?",
    rubric: [
      "Impulsive or shallow; no sign of deliberation",
      "Little reflection; quick, surface-level",
      "Some reflection and reasoning",
      "Clearly thoughtful and deliberative",
      "Deeply reflective, effortful, careful reasoning",
    ],
    note: "Inferred from a single message; the aggregate across messages is the more stable estimate.",
  },
  {
    id: "analytic_intuitive",
    category: "Cognitive",
    group: "cognitive-style",
    label: "Analytic vs. intuitive",
    polarity: "diagnostic",
    direction: "high = more analytic, systematic (vs. intuitive)",
    basis: "text",
    instructions: "How analytic and systematic (vs. intuitive and heuristic) is the thinking in this message?",
    rubric: [
      "Entirely intuitive, impressionistic, heuristic",
      "Mostly intuitive with little analysis",
      "Balanced analytic and intuitive",
      "Mostly analytic and systematic",
      "Rigorously analytic, structured, systematic",
    ],
  },
  {
    id: "tolerance_for_ambiguity",
    category: "Cognitive",
    group: "cognitive-style",
    label: "Tolerance for ambiguity",
    polarity: "diagnostic",
    direction: "high = more comfortable with ambiguity",
    basis: "text",
    instructions: "How comfortable is this message with open-ended, ambiguous, or unresolved situations?",
    rubric: [
      "Strongly uncomfortable with ambiguity; demands closure or certainty",
      "Mostly uncomfortable; seeks definite answers",
      "Moderate comfort with some ambiguity",
      "Comfortable with open-ended problems",
      "Highly comfortable with ambiguity and uncertainty",
    ],
  },
  {
    id: "abstraction_ability",
    category: "Cognitive",
    group: "cognitive-style",
    label: "Abstraction ability",
    polarity: "desirable",
    direction: "high = handles higher-order abstraction better",
    basis: "text",
    instructions: "How well does this message handle higher-order abstraction and conceptual generalization?",
    rubric: [
      "Strictly concrete; no abstraction",
      "Minimal abstraction; stays at surface level",
      "Some abstraction and generalization",
      "Comfortable with higher-order concepts",
      "Fluent, precise higher-order abstraction",
    ],
  },
  {
    id: "confidence_calibration",
    category: "Cognitive",
    group: "cognitive-style",
    label: "Confidence calibration",
    polarity: "desirable",
    direction: "high = confidence better matches what content warrants",
    basis: "text",
    instructions: "How well does the confidence expressed in this message match the warrant its content provides?",
    rubric: [
      "Grossly overconfident or underconfident relative to the content",
      "Poorly calibrated; confidence misaligned with evidence",
      "Partially calibrated",
      "Mostly well-calibrated confidence",
      "Confidence precisely matches what the content warrants",
    ],
    note: "Very weak from a single message without ground truth; treat with low trust.",
  },
  {
    id: "cognitive_rigidity",
    category: "Cognitive",
    group: "cognitive-style",
    label: "Cognitive rigidity",
    polarity: "inverted-risk",
    direction: "high = more fixed, closed to revising models",
    basis: "text",
    instructions: "How fixed and closed is this message to revising mental models or considering alternatives?",
    rubric: [
      "Very open; actively considers alternatives and revises",
      "Mostly open to alternatives",
      "Neutral; neither rigid nor flexible",
      "Fairly rigid; resists alternatives",
      "Extremely rigid, dogmatic, closed to revision",
    ],
  },

  // ---- C. Personality (Big Five) ----
  {
    id: "openness",
    category: "Personality (Big Five)",
    group: "personality-big-five",
    label: "Openness to experience",
    polarity: "diagnostic",
    direction: "high = more curious, novelty-seeking",
    basis: "text",
    instructions: "How much does this message indicate openness to experience (curiosity, novelty-seeking)?",
    rubric: [
      "No indication of curiosity or novelty-seeking",
      "Slight openness; occasional curiosity",
      "Moderate openness",
      "Clearly curious and novelty-seeking",
      "Strongly curious, exploratory, open to new ideas",
    ],
  },
  {
    id: "conscientiousness",
    category: "Personality (Big Five)",
    group: "personality-big-five",
    label: "Conscientiousness",
    polarity: "diagnostic",
    direction: "high = more disciplined, organized",
    basis: "text",
    instructions: "How much does this message indicate conscientiousness (discipline, organization, thoroughness)?",
    rubric: [
      "Disorganized, careless, haphazard",
      "Somewhat careless or unstructured",
      "Moderately organized",
      "Clearly disciplined and organized",
      "Highly disciplined, methodical, thorough",
    ],
  },
  {
    id: "extraversion",
    category: "Personality (Big Five)",
    group: "personality-big-five",
    label: "Extraversion",
    polarity: "diagnostic",
    direction: "high = more outgoing, social",
    basis: "text",
    instructions: "How much does this message indicate extraversion (outgoing, social energy)?",
    rubric: [
      "Highly reserved or withdrawn",
      "Introverted, low social energy",
      "Moderate sociability",
      "Outgoing and socially engaged",
      "Highly outgoing, gregarious, socially energetic",
    ],
  },
  {
    id: "agreeableness",
    category: "Personality (Big Five)",
    group: "personality-big-five",
    label: "Agreeableness",
    polarity: "diagnostic",
    direction: "high = more cooperative, warm",
    basis: "text",
    instructions: "How much does this message indicate agreeableness (cooperativeness, warmth)?",
    rubric: [
      "Antagonistic, cold, or uncooperative",
      "Somewhat distant or uncooperative",
      "Neutral warmth",
      "Cooperative and warm",
      "Highly cooperative, warm, trusting",
    ],
  },
  {
    id: "emotional_stability",
    category: "Personality (Big Five)",
    group: "personality-big-five",
    label: "Emotional stability",
    polarity: "diagnostic",
    direction: "high = more emotionally stable (inverse of neuroticism)",
    basis: "text",
    instructions: "How much does this message indicate emotional stability (calmness; inverse of neuroticism)?",
    rubric: [
      "Highly anxious, reactive, or distressed",
      "Somewhat anxious or emotionally reactive",
      "Moderate stability",
      "Calm and even-keeled",
      "Highly stable, composed, resilient",
    ],
  },

  // ---- D. Motivation & values ----
  {
    id: "risk_tolerance",
    category: "Motivation & Values",
    group: "motivation-values",
    label: "Risk tolerance",
    polarity: "diagnostic",
    direction: "high = more willing to take risk",
    basis: "text",
    instructions: "How much does this message indicate willingness to take risk?",
    rubric: [
      "Strongly risk-averse; avoids uncertainty",
      "Mostly risk-averse",
      "Balanced risk stance",
      "Comfortable with risk",
      "Strongly risk-seeking",
    ],
    note: "Weak from a single message; the aggregate is more reliable.",
  },
  {
    id: "promotion_prevention",
    category: "Motivation & Values",
    group: "motivation-values",
    label: "Promotion vs. prevention focus",
    polarity: "diagnostic",
    direction: "high = more promotion-focused (growth-seeking vs. safety)",
    basis: "text",
    instructions: "How much is this message oriented toward promotion (growth, gains) vs. prevention (safety, avoiding loss)?",
    rubric: [
      "Strongly prevention-focused; safety and avoiding loss dominate",
      "Mostly prevention-focused",
      "Balanced promotion and prevention",
      "Mostly promotion-focused",
      "Strongly promotion-focused; growth and gains dominate",
    ],
  },
  {
    id: "persistence_grit",
    category: "Motivation & Values",
    group: "motivation-values",
    label: "Persistence / grit",
    polarity: "diagnostic",
    direction: "high = more persistent through difficulty",
    basis: "text",
    instructions: "How much does this message indicate persistence and grit through difficulty?",
    rubric: [
      "Gives up easily; avoids difficulty",
      "Low persistence",
      "Moderate persistence",
      "Clearly persistent",
      "Highly persistent, determined, gritty",
    ],
  },
  {
    id: "intrinsic_motivation",
    category: "Motivation & Values",
    group: "motivation-values",
    label: "Intrinsic motivation",
    polarity: "diagnostic",
    direction: "high = more internally driven (vs. extrinsic)",
    basis: "text",
    instructions: "How much does this message indicate intrinsic (internally driven) vs. extrinsic motivation?",
    rubric: [
      "Purely extrinsic; driven by external reward or pressure",
      "Mostly extrinsic",
      "Mixed intrinsic and extrinsic",
      "Mostly intrinsic",
      "Strongly intrinsic; driven by interest and mastery",
    ],
  },

  // ---- E. Affective / emotional ----
  {
    id: "empathy_expressed",
    category: "Affective / Emotional",
    group: "affective-emotional",
    label: "Empathy (expressed)",
    polarity: "diagnostic",
    direction: "high = more empathic, perspective-taking",
    basis: "text",
    instructions: "How empathic and perspective-taking is this message toward others?",
    rubric: [
      "No empathy; dismissive of others' perspective",
      "Low empathy",
      "Some empathy or acknowledgment",
      "Clearly empathic and perspective-taking",
      "Deeply empathic; consistently takes others' perspective",
    ],
  },
  {
    id: "self_disclosure",
    category: "Affective / Emotional",
    group: "affective-emotional",
    label: "Self-disclosure",
    polarity: "diagnostic",
    direction: "high = more personal detail shared",
    basis: "text",
    instructions: "How much personal, private detail does this message share?",
    rubric: [
      "No personal disclosure; entirely impersonal",
      "Minimal personal detail",
      "Some personal detail",
      "Significant personal disclosure",
      "Extensive, intimate self-disclosure",
    ],
    note: "Privacy-sensitive; only the aggregate is reported and no excerpt is ever stored.",
  },
  {
    id: "affect_intensity",
    category: "Affective / Emotional",
    group: "affective-emotional",
    label: "Affect intensity",
    polarity: "diagnostic",
    direction: "high = more intense emotional expression",
    basis: "text",
    instructions: "How intense is the emotional expression in this message?",
    rubric: [
      "Flat, muted, or no emotional expression",
      "Mild emotional expression",
      "Moderate intensity",
      "Strong emotional expression",
      "Extremely intense, dramatic emotional expression",
    ],
  },
  {
    id: "frustration_hostility",
    category: "Affective / Emotional",
    group: "affective-emotional",
    label: "Frustration / hostility",
    polarity: "inverted-risk",
    direction: "high = more frustrated, hostile",
    basis: "text",
    instructions: "How frustrated or hostile is this message?",
    rubric: [
      "No frustration or hostility",
      "Mild irritation or negativity",
      "Moderate frustration",
      "Clear hostility or anger",
      "Intense hostility, aggression, or rage",
    ],
  },

  // ---- F. Domain aptitude ----
  {
    id: "technical_depth",
    category: "Domain Aptitude",
    group: "domain-aptitude",
    label: "Technical depth",
    polarity: "diagnostic",
    direction: "high = deeper, more expert domain knowledge",
    basis: "text",
    instructions: "How deep and expert is the domain/technical knowledge shown in this message?",
    rubric: [
      "No technical depth; surface-level",
      "Basic familiarity",
      "Working knowledge",
      "Strong, deep expertise",
      "Expert-level, advanced domain mastery",
    ],
  },
  {
    id: "mental_model_correctness",
    category: "Domain Aptitude",
    group: "domain-aptitude",
    label: "Mental-model correctness",
    polarity: "desirable",
    direction: "high = conceptual model better matches reality",
    basis: "text",
    instructions: "How well does the conceptual model implied by this message match how things actually work?",
    rubric: [
      "Fundamentally mistaken mental model",
      "Mostly incorrect conceptual model",
      "Partially correct with gaps",
      "Largely correct mental model",
      "Precisely correct, accurate conceptual model",
    ],
    note: "Depends on domain ground truth; low trust without verification.",
  },
  {
    id: "vocabulary_sophistication",
    category: "Domain Aptitude",
    group: "domain-aptitude",
    label: "Vocabulary sophistication",
    polarity: "diagnostic",
    direction: "high = more precise domain terminology",
    basis: "text",
    instructions: "How precise and sophisticated is the terminology used in this message?",
    rubric: [
      "Very basic, imprecise vocabulary",
      "Simple, everyday vocabulary",
      "Moderately precise terminology",
      "Precise, domain-appropriate terminology",
      "Highly precise, sophisticated technical vocabulary",
    ],
  },
  {
    id: "debugging_orientation",
    category: "Domain Aptitude",
    group: "domain-aptitude",
    label: "Debugging orientation",
    polarity: "desirable",
    direction: "high = more systematic error-isolation",
    basis: "text",
    instructions: "How systematic is this message's error-isolation / debugging approach?",
    rubric: [
      "No systematic approach; blames or guesses",
      "Haphazard or trial-and-error",
      "Some structure to isolating the problem",
      "Systematic error-isolation",
      "Rigorously methodical, hypothesis-driven debugging",
    ],
  },

  // ---- G. Interaction / behavioral ----
  {
    id: "engagement",
    category: "Interaction / Behavioral",
    group: "interaction-behavioral",
    label: "Engagement",
    polarity: "diagnostic",
    direction: "high = more persistent, deeper involvement",
    basis: "text",
    instructions: "How persistent and deeply involved is this message in the interaction?",
    rubric: [
      "Detached, minimal involvement",
      "Low engagement",
      "Moderate engagement",
      "Clearly engaged and invested",
      "Deeply engaged, persistent, highly involved",
    ],
  },
  {
    id: "help_seeking_style",
    category: "Interaction / Behavioral",
    group: "interaction-behavioral",
    label: "Help-seeking style",
    polarity: "diagnostic",
    direction: "high = more proactive, direct help-seeking",
    basis: "text",
    instructions: "How proactive and direct (vs. passive and indirect) is this message's help-seeking?",
    rubric: [
      "Very passive; hints or complains without asking",
      "Indirect or vague request for help",
      "Moderately direct request",
      "Proactive, direct request",
      "Highly proactive, precise, direct help-seeking",
    ],
  },
  {
    id: "self_correction",
    category: "Interaction / Behavioral",
    group: "interaction-behavioral",
    label: "Self-correction",
    polarity: "desirable",
    direction: "high = more willing to revise own errors",
    basis: "text",
    instructions: "How willing is this message to acknowledge and revise its own errors?",
    rubric: [
      "Never acknowledges or revises errors; defensive",
      "Rarely self-corrects",
      "Occasionally acknowledges errors",
      "Willingly revises own errors",
      "Actively seeks out and corrects own mistakes",
    ],
  },
  {
    id: "escalation_readiness",
    category: "Interaction / Behavioral",
    group: "interaction-behavioral",
    label: "Escalation readiness",
    polarity: "inverted-risk",
    direction: "high = more likely to escalate or blame external causes",
    basis: "text",
    instructions: "How likely is this message to escalate or attribute problems to external causes or blame others?",
    rubric: [
      "Takes ownership; no blame or escalation",
      "Mostly constructive; little blame",
      "Some external attribution",
      "Frequently blames external causes or escalates",
      "Highly escalated; strongly blames others or external causes",
    ],
  },
];

/** Category display labels in group order. */
export const CATEGORIES: readonly string[] = GROUP_ORDER.map((group) => group.label);

/** Number of rubric levels minus one; normalized score = answer.score / this. */
export const RUBRIC_MAX = 4;
